---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_xdebug_module_path.
  set_fact:
    php_xdebug_module_path: "{{ __php_xdebug_module_path }}"
  when: php_xdebug_module_path is not defined

- name: Define php_xdebug_config_filename.
  set_fact:
    php_xdebug_config_filename: "{{ __php_xdebug_config_filename }}"
  when: php_xdebug_config_filename is not defined

- include_tasks: install-from-source.yml
  when: php_version is version('7.0', '>')

- include_tasks: install-from-repository.yml
  when: php_version is version('7.0', '<=')

- include_tasks: configure.yml
